#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

busybox clear
busybox echo ""
free | awk '/Mem/{print ">>>...Memory Before Boosting: "$4/1024" MB";}'
busybox sleep 1
busybox echo ""
busybox echo "Dropping cache"
sync
busybox sleep 1
busybox echo "3" > /proc/sys/vm/drop_caches
busybox sleep 1
dc=/proc/sys/vm/drop_caches
dc_v=`cat $dc`
if [ "$dc_v" -gt 1 ]; then
	busybox echo "1" > /proc/sys/vm/drop_caches
fi
busybox echo ""
busybox echo ""
busybox echo "BOOSTED!!!"
busybox echo ""
busybox echo ""
free | awk '/Mem/{print ">>>...Memory After Boosting : "$4/1024" MB";}'
busybox sleep 3
