#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
# Thanks to @JRummy16 and @ArjunrambZ
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /data
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /data
busybox mount -o remount,rw /system

echo "root:x:0:0::data/cron:/system/xbin/bash" > /system/etc/passwd
ln -s /system/xbin /xbin
	
# set timezone (if you're not between -0500 and -0800 you get PST)
# todo - support other timezones
timezone=`date +%z`
if busybox [ $timezone = "-0800" ]; then
	TZ=PST8PDT
elif busybox [ $timezone = "-0700" ]; then
	TZ=MST7MDT
elif busybox [ $timezone = "-0600" ]; then
	TZ=CST6CDT
elif busybox [ $timezone = "-0500" ]; then
	TZ=EST5EDT
else
	TZ=PST8PDT
fi
export TZ
	
# use /data/cron, call the crontab file "root"
if busybox [ ! -d /data/cron ]; then
	busybox mkdir -p /data/cron
	busybox cat >> /data/cron/root
# run-parts
01 * * * * busybox run-parts /system/etc/cron/cron.hourly
02 4 * * * busybox run-parts /system/etc/cron/cron.daily
22 4 * * 0 busybox run-parts /system/etc/cron/cron.weekly
fi
busybox crond -c /data/cron
