#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/Net_tweaks.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log" | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Adding Net tweaks..." | tee -a $LS

busybox sleep 10

busybox chmod 644 /proc/sys/net/*
	busybox sysctl -e -w net.unix.max_dgram_qlen=50;
	busybox sysctl -e -w net.ipv4.tcp_moderate_rcvbuf=1;
	busybox sysctl -e -w net.ipv4.route.flush=1;
	busybox sysctl -e -w net.ipv4.udp_rmem_min=6144;
	busybox sysctl -e -w net.ipv4.udp_wmem_min=6144;
	busybox sysctl -e -w net.ipv4.tcp_rfc1337=1;
	busybox sysctl -e -w net.ipv4.ip_no_pmtu_disc=0;
	busybox sysctl -e -w net.ipv4.tcp_ecn=0;
	busybox sysctl -e -w net.ipv4.tcp_timestamps=0;
	busybox sysctl -e -w net.ipv4.tcp_sack=1;
	busybox sysctl -e -w net.ipv4.tcp_fack=1;
	busybox sysctl -e -w net.ipv4.tcp_window_scaling=1;
	busybox sysctl -e -w net.ipv4.tcp_tw_recycle=1;
	busybox sysctl -e -w net.ipv4.tcp_tw_reuse=1;
	busybox sysctl -e -w net.ipv4.tcp_congestion_control=cubic;
	busybox sysctl -e -w net.ipv4.tcp_syncookies=1;
	busybox sysctl -e -w net.ipv4.tcp_synack_retries=2;
	busybox sysctl -e -w net.ipv4.tcp_syn_retries=2;
	busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024;
	busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=16384; 
	busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1;
	busybox sysctl -e -w net.ipv4.icmp_echo_ignore_broadcasts=1;
	busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1;
	busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1;
	busybox sysctl -e -w net.ipv4.tcp_fin_timeout=15;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5;
	busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1800;
	busybox sysctl -e -w net.ipv4.ip_forward=0;
	busybox sysctl -e -w net.ipv4.conf.all.send_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.send_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1;
	busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1;
	busybox sysctl -e -w net.ipv4.conf.all.accept_source_route=0;
	busybox sysctl -e -w net.ipv4.conf.default.accept_source_route=0 ;
	busybox sysctl -e -w net.ipv4.conf.all.accept_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.accept_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.all.secure_redirects=0;
	busybox sysctl -e -w net.ipv4.conf.default.secure_redirects=0;

busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Net tweaks added" | tee -a $LS
