#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/SD_tweak.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log" | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Adding SD speed tweak..." | tee -a $LS

busybox sleep 10

#RAM=$((`awk '/MemTotal/{print $2}' /proc/meminfo`/1024))
#L=$(((RAM/64+1)*128))
L=1024

#busybox echo "...Your RAM is $RAM..." | tee -a $LS
#busybox echo "...Value calculated based on your Ram..." | tee -a $LS

MMC=`busybox ls -d /sys/block/mmc* 2>/dev/null`;
for S in $MMC;
do
	if [ -e $S/queue/read_ahead_kb ];
	then
		busybox echo "$L" >  $S/queue/read_ahead_kb;
	fi;
	if [ -e $S/bdi/read_ahead_kb ];
        then
              busybox echo "$L" >  $S/bdi/read_ahead_kb;
        fi;
done

busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) SD speed tweak added" | tee -a $LS
