#!/system/bin/sh
# L SPEED MOD
# Copyright (C) 2015 Paget96
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

LS=/system/etc/L_SPEED/00L_STUFF/LOGS/Ram_manager.log

busybox rm -f $LS
busybox touch $LS

busybox echo "# L Speed log " | tee -a $LS
busybox echo "" | tee -a $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) Tweaking minfree values & adj lowmem values..." | tee -a $LS

busybox sleep 10

# Cost
if [ -e /sys/module/lowmemorykiller/parameters/cost ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/cost
    busybox echo "8" > /sys/module/lowmemorykiller/parameters/cost
  fi

# Debug level
if [ -e /sys/module/lowmemorykiller/parameters/debug_level ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/debug_level
    busybox echo "0" > /sys/module/lowmemorykiller/parameters/debug_level
  fi

# ADJ Values
if [ -e /sys/module/lowmemorykiller/parameters/adj ]; then
    busybox chmod 644 /sys/module/lowmemorykiller/parameters/adj
    busybox echo "0,1,3,5,7,15" > /sys/module/lowmemorykiller/parameters/adj
   fi

# Minfree Values 
mem=`free|grep Mem | awk '{print $2}'`

#512 and less
oom11=14
oom21=19
oom31=24
oom41=37
oom51=43
oom61=51

lmk11=$(($oom11*1024/4));
lmk21=$(($oom21*1024/4));
lmk31=$(($oom31*1024/4));
lmk41=$(($oom41*1024/4));
lmk51=$(($oom51*1024/4));
lmk61=$(($oom61*1024/4));

#768
oom12=21
oom22=29
oom32=47
oom42=64
oom52=73
oom62=82

lmk12=$(($oom12*1024/4));
lmk22=$(($oom22*1024/4));
lmk32=$(($oom32*1024/4));
lmk42=$(($oom42*1024/4));
lmk52=$(($oom52*1024/4));
lmk62=$(($oom62*1024/4));

#1024
oom13=27
oom23=37
oom33=48
oom43=72
oom53=83
oom63=98

lmk13=$(($oom13*1024/4));
lmk23=$(($oom23*1024/4));
lmk33=$(($oom33*1024/4));
lmk43=$(($oom43*1024/4));
lmk53=$(($oom53*1024/4));
lmk63=$(($oom63*1024/4));

#1024+
oom14=53
oom24=72
oom34=93
oom44=140
oom54=161
oom64=190

lmk14=$(($oom14*1024/4));
lmk24=$(($oom24*1024/4));
lmk34=$(($oom34*1024/4));
lmk44=$(($oom44*1024/4));
lmk54=$(($oom54*1024/4));
lmk64=$(($oom64*1024/4));

if [ "$mem" -lt 512000 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk11,$lmk21,$lmk31,$lmk41,$lmk51,$lmk61" > /sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 768000 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk12,$lmk22,$lmk32,$lmk42,$lmk52,$lmk62" >/sys/module/lowmemorykiller/parameters/minfree
elif [ "$mem" -lt 1024000 ]; then
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk13,$lmk23,$lmk33,$lmk43,$lmk53,$lmk63" > /sys/module/lowmemorykiller/parameters/minfree
else 
	busybox chmod 644 /sys/module/lowmemorykiller/parameters/minfree
	busybox echo "$lmk14,$lmk24,$lmk34,$lmk44,$lmk54,$lmk64" > /sys/module/lowmemorykiller/parameters/minfree
fi

busybox echo "" >> $LS
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ) RAM manager successfully applied.." | busybox tee -a $LS
